server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pblgllgs/config-server-microservices-sb2
          default-label: master
          search-paths: configurations
          clone-on-start: true
  application:
    name: config-service